#image: jsherz/base-java-container:openjdk-11-buster
image: scm.int.jsherz.com:5005/jsherz/base-java-container

stages:
  - lint
  - test

lint:
  tags:
    - docker
  stage: lint
  script:
    - sbt scalastyle
    - sbt test:scalastyle

test:
  tags:
    - docker
  stage: test
  script:
    - sbt coverage test coverageReport
  artifacts:
    when: always
    paths:
      - ./target/test-reports/*.xml
      - ./target/scala-2.13/scoverage-report/**/*
      - ./target/scala-2.13/scoverage-report/*
    reports:
      junit:
        - ./target/test-reports/*.xml
